// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.webhunter.domain;

import com.webhunter.domain.UserProfile;
import com.webhunter.domain.UserProfileDataOnDemand;
import com.webhunter.domain.UserProfileIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect UserProfileIntegrationTest_Roo_IntegrationTest {
    
    declare @type: UserProfileIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: UserProfileIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: UserProfileIntegrationTest: @Transactional;
    
    @Autowired
    private UserProfileDataOnDemand UserProfileIntegrationTest.dod;
    
    @Test
    public void UserProfileIntegrationTest.testCountUserProfiles() {
        Assert.assertNotNull("Data on demand for 'UserProfile' failed to initialize correctly", dod.getRandomUserProfile());
        long count = UserProfile.countUserProfiles();
        Assert.assertTrue("Counter for 'UserProfile' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void UserProfileIntegrationTest.testFindUserProfile() {
        UserProfile obj = dod.getRandomUserProfile();
        Assert.assertNotNull("Data on demand for 'UserProfile' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserProfile' failed to provide an identifier", id);
        obj = UserProfile.findUserProfile(id);
        Assert.assertNotNull("Find method for 'UserProfile' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'UserProfile' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void UserProfileIntegrationTest.testFindAllUserProfiles() {
        Assert.assertNotNull("Data on demand for 'UserProfile' failed to initialize correctly", dod.getRandomUserProfile());
        long count = UserProfile.countUserProfiles();
        Assert.assertTrue("Too expensive to perform a find all test for 'UserProfile', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<UserProfile> result = UserProfile.findAllUserProfiles();
        Assert.assertNotNull("Find all method for 'UserProfile' illegally returned null", result);
        Assert.assertTrue("Find all method for 'UserProfile' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void UserProfileIntegrationTest.testFindUserProfileEntries() {
        Assert.assertNotNull("Data on demand for 'UserProfile' failed to initialize correctly", dod.getRandomUserProfile());
        long count = UserProfile.countUserProfiles();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<UserProfile> result = UserProfile.findUserProfileEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'UserProfile' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'UserProfile' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void UserProfileIntegrationTest.testFlush() {
        UserProfile obj = dod.getRandomUserProfile();
        Assert.assertNotNull("Data on demand for 'UserProfile' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserProfile' failed to provide an identifier", id);
        obj = UserProfile.findUserProfile(id);
        Assert.assertNotNull("Find method for 'UserProfile' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyUserProfile(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'UserProfile' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UserProfileIntegrationTest.testMergeUpdate() {
        UserProfile obj = dod.getRandomUserProfile();
        Assert.assertNotNull("Data on demand for 'UserProfile' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserProfile' failed to provide an identifier", id);
        obj = UserProfile.findUserProfile(id);
        boolean modified =  dod.modifyUserProfile(obj);
        Integer currentVersion = obj.getVersion();
        UserProfile merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'UserProfile' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UserProfileIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'UserProfile' failed to initialize correctly", dod.getRandomUserProfile());
        UserProfile obj = dod.getNewTransientUserProfile(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'UserProfile' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'UserProfile' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'UserProfile' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void UserProfileIntegrationTest.testRemove() {
        UserProfile obj = dod.getRandomUserProfile();
        Assert.assertNotNull("Data on demand for 'UserProfile' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UserProfile' failed to provide an identifier", id);
        obj = UserProfile.findUserProfile(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'UserProfile' with identifier '" + id + "'", UserProfile.findUserProfile(id));
    }
    
}
