// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.webhunter.domain;

import com.webhunter.domain.UserProfileDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect UserProfileDataOnDemand_Roo_Configurable {
    
    declare @type: UserProfileDataOnDemand: @Configurable;
    
}
